import { Residue } from '../types/residue';

export const defaultResidues: Residue[] = [
  {
    id: 'RES-0001',
    weight: 1000,
    humidity: 65,
    ph: 6.8,
    volume: 2.5,
    supplier: 'Local Farm A',
    location: 'North Field',
    description: 'Fresh grass clippings',
    cnRatio: 17,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0002',
    weight: 800,
    humidity: 15,
    ph: 6.5,
    volume: 4.0,
    supplier: 'Wood Mill B',
    location: 'Storage Unit 1',
    description: 'Sawdust',
    cnRatio: 325,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0003',
    weight: 500,
    humidity: 80,
    ph: 6.2,
    volume: 1.2,
    supplier: 'Restaurant C',
    location: 'Kitchen Waste Bin',
    description: 'Food scraps',
    cnRatio: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0004',
    weight: 1200,
    humidity: 35,
    ph: 7.0,
    volume: 3.0,
    supplier: 'Garden Center D',
    location: 'Compost Area',
    description: 'Fallen leaves',
    cnRatio: 60,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0005',
    weight: 300,
    humidity: 75,
    ph: 6.9,
    volume: 0.8,
    supplier: 'Coffee Shop E',
    location: 'Waste Collection',
    description: 'Coffee grounds',
    cnRatio: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0006',
    weight: 900,
    humidity: 45,
    ph: 6.7,
    volume: 2.2,
    supplier: 'Farm F',
    location: 'Barn Storage',
    description: 'Straw',
    cnRatio: 80,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0007',
    weight: 400,
    humidity: 85,
    ph: 6.4,
    volume: 1.0,
    supplier: 'Market G',
    location: 'Produce Section',
    description: 'Vegetable waste',
    cnRatio: 13,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0008',
    weight: 600,
    humidity: 20,
    ph: 6.6,
    volume: 1.5,
    supplier: 'Paper Mill H',
    location: 'Recycling Area',
    description: 'Cardboard',
    cnRatio: 350,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0009',
    weight: 700,
    humidity: 70,
    ph: 7.1,
    volume: 1.8,
    supplier: 'Brewery I',
    location: 'Waste Storage',
    description: 'Spent grain',
    cnRatio: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'RES-0010',
    weight: 1100,
    humidity: 30,
    ph: 6.8,
    volume: 2.8,
    supplier: 'Landscaper J',
    location: 'Yard Waste',
    description: 'Wood chips',
    cnRatio: 400,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];